# Generated by Django 3.2.9 on 2021-12-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='continent_name',
            field=models.CharField(default='Africa', max_length=200),
        ),
    ]
