# Generated by Django 3.2.9 on 2021-12-03 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schooladdress_street', models.CharField(max_length=200)),
                ('schooladdress_pob', models.CharField(max_length=200)),
                ('schooladdress_stateprovince', models.CharField(max_length=200)),
                ('schooladdress_postalcode', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.city')),
            ],
        ),
    ]
