# Generated by Django 3.2.9 on 2021-12-06 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_schooladdress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schooltype_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_img', models.ImageField(blank=True, upload_to='img/school/%Y/%m/%d/')),
                ('school_program', models.CharField(max_length=200)),
                ('school_programdesc', models.TextField(blank=True, null=True)),
                ('school_url', models.URLField()),
                ('school_pub_date', models.DateTimeField(verbose_name='date published')),
                ('schooltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schooltype')),
            ],
        ),
    ]
