# Generated by Django 3.2.9 on 2021-12-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_schooltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_imgname', models.CharField(default='School', max_length=200)),
                ('school_imgdesc', models.CharField(blank=True, default='School', max_length=200, null=True)),
                ('school_imgsourcename', models.CharField(blank=True, default='School', max_length=200, null=True)),
                ('school_imgurlmain', models.ImageField(blank=True, upload_to='img/school/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_img',
        ),
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schoolimage'),
        ),
    ]
