# Generated by Django 3.2.9 on 2021-12-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_auto_20211206_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city_name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['region_name'], 'verbose_name_plural': 'Region'},
        ),
    ]
