# Generated by Django 3.2.9 on 2021-12-06 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20211206_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='image',
        ),
        migrations.AddField(
            model_name='schoolimage',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
