# Generated by Django 3.2.9 on 2021-12-06 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20211206_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='schooltype',
        ),
        migrations.AddField(
            model_name='schooltype',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
