# Generated by Django 3.2.9 on 2021-12-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_auto_20211206_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolimage',
            name='school',
        ),
        migrations.RemoveField(
            model_name='schooltype',
            name='school',
        ),
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schoolimage'),
        ),
        migrations.AddField(
            model_name='school',
            name='schooltype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schooltype'),
        ),
    ]
