# Generated by Django 3.2.9 on 2021-12-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20211206_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.ManyToManyField(to='schools.SchoolAddress'),
        ),
    ]
