# Generated by Django 3.2.9 on 2021-12-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_schoolimage_school_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolimage',
            name='school_status',
        ),
        migrations.AddField(
            model_name='school',
            name='school_status',
            field=models.CharField(blank=True, choices=[('AC', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2, null=True),
        ),
    ]
