# Generated by Django 3.2.9 on 2021-12-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_auto_20211212_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
