# Generated by Django 3.2.9 on 2021-12-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_school_school_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_slug',
            new_name='slug',
        ),
    ]
